### ISSUE TITLE
Can't connect (GB)

### ISSUE THREAD

**Issue by 0xKiwan** [Sholofly/arrisdcx960#35]
**Describe the bug**
Getting can't connect when setting up the custom integration

**To Reproduce**

Attempt to sign into your VM account

![Screenshot 2022-08-04 135245](https://user-images.githubusercontent.com/22123241/182851686-81f81dc5-b5d7-4ee6-8d51-8d9159980d4b.png)

**Comment by legi1** [comment]
Same here in Switzerland with UPC Box (about 4 years old).

**Comment by Sholofly** [comment]
Hi! Sorry for the huge delay in my responses. Unfortunately the logging on the Ziggogo.tv site isn't accessible anymore. Therefore it's hard for me to debug or reverse engineer stuff. Besides that  I really could use en extra hand to go through my current Python code to review and make it more stable, since that's the issue now. So if you know someone...

**Comment by Sholofly** [comment]
Component is broken for all users. I'm creating a new one: https://github.com/Sholofly/lghorizon
For now this is only available for Dutch (Ziggo) users but i'm planning to support the others too
