### ISSUE TITLE
Can't connect (Ziggo)

### ISSUE THREAD

**Issue by Jordenjj** [Sholofly/arrisdcx960#36]
Whenever I enter my details, I get a can't connect error. This is on the ziggo mediabox next mini. It seems HA logs do not show any errors so im afraid I don't have any more information.

**Comment by Jordenjj** [comment]
A day later, I try a again and it works. Very strange.

**Comment by Sholofly** [comment]
Hi! Sorry for the huge delay in my responses. Unfortunately the logging on the Ziggogo.tv site isn't accessible anymore. Therefore it's hard for me to debug or reverse engineer stuff. Besides that  I really could use en extra hand to go through my current Python code to review and make it more stable, since that's the issue now. So if you know someone...
